# Generated by Django 5.0.1 on 2024-01-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='پسوورد'),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='نام کاربری'),
        ),
    ]
