# Generated by Django 5.0.1 on 2024-01-29 15:23

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=255, verbose_name='نام')),
                ('code', models.CharField(max_length=255, verbose_name='کد')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
            ],
            options={
                'verbose_name': 'پروکسی',
                'verbose_name_plural': 'پروکسی ها',
            },
        ),
    ]
